name: server_logger
version: 1.0.0
author: Brandon White <jennexproject+serverlogger@gmail.com>
description: A basic logging helper for server-side projects.
homepage: https://google.com/+BrandonWhite
