name: server_logger
version: 1.0.1
author: Brandon White <jennexproject+serverlogger@gmail.com>
description: A basic logging helper for server-side projects.
homepage: https://google.com/+BrandonWhite
environment:
  sdk: '>=1.9.0 <3.0.0'